server:
  port: 8072
spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8090/realms/booking-microservices/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: booking-microservices-user
            client-secret: 8ekZimKROp7kKzmPlemdJcuCwHG02bCn
            authorization-grant-type: client_credentials
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/booking-microservices
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-server
        url: /v3/api-docs
      - name: user-service
        url: /users/v3/api-docs
      - name: ticket-service
        url: /tickets/v3/api-docs
info:
  app:
    name: "API Gateway"
    description: "API Gateway"
    version: "1.0.0"
logging:
  level:
    org:
    springframework: INFO
    com:
      microservice:
        gatewayserver: DEBUG
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000