server:
  port: 8081
spring:
  application:
    name: bookings
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    config:
      enabled: true
  datasource:
    url: "jdbc:mysql://localhost:3306/booking"
    username: "root"
    password: "12345"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  debug: true
info:
  app:
    name: "tickets"
    description: "API for tickets"
    version: "1.0.0"
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui.html
logging:
  level:
    org:
      springframework: INFO
    com:
      microservice:
        tickets: DEBUG
